### ISSUE TITLE
movable-value constraints on callables is specified incorrectly

### ISSUE THREAD

**Issue by ericniebler** [cplusplus/sender-receiver#171] opened 2023-12-26 21:24 UTC
From [exec.let]:

> let `F` be the decayed type of `f`. If [...] `F` does not satisfy *`movable-value`*, the expression <code><i>let-cpo</i>(sndr, f)</code> is ill-formed.

If `f` is an lvalue reference to a move-only type, then `F` satisfies *`movable-value`*, but we can't use `f` to initialize an `F` object, which is what the `let_` algorithms need.

Respecify as "If [...] `decltype((f))` does not satisfy *`movable-value`*, [...]".

In [exec.let] and elsewhere.

**Comment by lewissbaker** [comment] 2024-07-04 05:57
Duplicate of #232, which has now been addressed in P2300R10.

**Closed by lewissbaker** 2024-07-04 05:57 UTC
Labels: bug, P1
